package com.bala.nested_objects_gdt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class A implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.bala.nested_objects_gdt.B refB;

	private java.lang.String x;

	public A() {
	}

	public com.bala.nested_objects_gdt.B getRefB() {
		return this.refB;
	}

	public void setRefB(com.bala.nested_objects_gdt.B refB) {
		this.refB = refB;
	}

	public java.lang.String getX() {
		return this.x;
	}

	public void setX(java.lang.String x) {
		this.x = x;
	}

	public A(com.bala.nested_objects_gdt.B refB, java.lang.String x) {
		this.refB = refB;
		this.x = x;
	}

}