package com.bala.nested_objects_gdt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class B implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.bala.nested_objects_gdt.C refC;

	public B() {
	}

	public com.bala.nested_objects_gdt.C getRefC() {
		return this.refC;
	}

	public void setRefC(com.bala.nested_objects_gdt.C refC) {
		this.refC = refC;
	}

	public B(com.bala.nested_objects_gdt.C refC) {
		this.refC = refC;
	}

}