package com.bala.nested_objects_gdt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class C implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.bala.nested_objects_gdt.D refD;

	public C() {
	}

	public com.bala.nested_objects_gdt.D getRefD() {
		return this.refD;
	}

	public void setRefD(com.bala.nested_objects_gdt.D refD) {
		this.refD = refD;
	}

	public C(com.bala.nested_objects_gdt.D refD) {
		this.refD = refD;
	}

}