package com.bala.nested_objects_gdt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class D implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer length;

	public D() {
	}

	public java.lang.Integer getLength() {
		return this.length;
	}

	public void setLength(java.lang.Integer length) {
		this.length = length;
	}

	public D(java.lang.Integer length) {
		this.length = length;
	}

}